### Recuperar todos los juegos
GET http://localhost:4000/api/store

### Recuperar la id de los juegos
GET http://localhost:4000/api/store/8

### Recuperar la id de los juegos
GET http://localhost:4000/api/store?genre=multijugador

###
GET http://localhost:4000/api/user

###
GET http://localhost:4000/api/users

###
GET https://store-megagames.onrender.com/api/users

###
POST https://store-megagames.onrender.com/api/users