[build]
publish = "."
functions = "netlify/functions"

[[redirects]]
from = "/about"
to = "/sites/about.html"
status = 200

[[redirects]]
from = "/ActivisionPublisherSale2024"
to = "/sites/ActivisionPublisherSale2024.html"
status = 200

[[redirects]]
from = "/cart"
to = "/sites/cart.html"
status = 200

[[redirects]]
from = "/community"
to = "/sites/community.html"
status = 200

[[redirects]]
from = "/games-details"
to = "/sites/games-details.html"
status = 200

[[redirects]]
from = "/gift-details"
to = "/sites/gift-details.html"
status = 200

[[redirects]]
from = "/help"
to = "/sites/help.html"
status = 200

[[redirects]]
from = "/juegos-populares"
to = "/sites/juegos-populares.html"
status = 200

[[redirects]]
from = "/juegos-y-tarjetas"
to = "/sites/juegos-y-tarjetas.html"
status = 200

[[redirects]]
from = "/notifications"
to = "/sites/notifications.html"
status = 200

[[redirects]]
from = "/ofertas-especiales"
to = "/sites/ofertas-especiales.html"
status = 200

[[redirects]]
from = "/offer-details"
to = "/sites/offer-details.html"
status = 200

[[redirects]]
from = "/publisher-sale-details"
to = "/sites/publisher-sale-details.html"
status = 200
